### ISSUE TITLE
improve default behavior of the module

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-jdbc#2]
I think we could do the following improvements:

- [ ] Capture metrics regardless of having a current trace context or not.
- [ ] We have some regular expressions there to detect the type of query, but at the end we are just storing metrics for reads and writes, we could get rid of those regex evaluations and measure calls to `java.sql.PreparedStatement#executeQuery` and `java.sql.PreparedStatement#executeUpdate` to get the same metrics.
- [ ] Include a minMaxCounter that tracks how many operations are currently executing against the database.
- [ ] Add the most common JDBC packages drivers into the default `aop.xml` to ensure that for most people it will just work out of the box.
- [ ] Add a configuration to decide whether the user wants trace-segments to be generated for the tracked JDBC calls, if so we should avoid using special characters in the default names (e.g. `Jdbc[Select]`).

Another thing that might be cool is to be able to separate metrics by connection pool, but that can come later.

**Comment by ivantopo** [comment]
after digging a bit, I realized that we cannot just use `executeQuery` and `executeUpdate` to differentiate between reads and writes, as there are more general methods like `execute` or `executeBatch` that could do pretty much anything, even combine types of queries within a batch... at this point, it seems more appropriate to differentiate between the call categories: queries, updates, batches and generic. 

wdyt @dpsoft?

**Comment by dpsoft** [comment]
@ivantopo I agree with you and also the idea of removing the regex that we are using to identify the query types and avoid performance issues.
