### ISSUE TITLE
Hikari pool metrics are not reported

### ISSUE THREAD

**Issue by htimur** [kamon-io/kamon-jdbc#4]
We are using `kamon-jdbc` with Play 2.5 and Slick 3.1.1, for some reason kamon reporting all metrics for the `hikari-pool.db_default` as 0, even though slick is using the hikaricp pool.

**Comment by ivantopo** [comment]
could you please tell us what Hikari version is ending up in your classpath?

**Comment by htimur** [comment]
@ivantopo it's `HikariCP-java6: 2.3.7`

**Comment by ivantopo** [comment]
oh, that's probably the issue. The instrumentation targets Hikari 2.6.x, we have a few users that have Play 2.4 and 2.5 running with Hikari 2.6.0 and it works fine, upgrading should solve the issue.

btw, are you actually running on Java 6?

**Comment by htimur** [comment]
@ivantopo ok thanks, will update the version and let you know. We are running on java8, but seems the dependancy is the old one.

**Comment by htimur** [comment]
@ivantopo After upgrading HikariCP to the latest version Kamon started reporting JDBC metrics. Thanks for help!
